# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build all  platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
    
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
    runs-on: ${{ matrix.macos }} 
    strategy:
      fail-fast: false
      matrix:
        xcode: ['latest']
        macos: ['macos-13']
        scheme: ['Taskr']
        command: ['build']
        platform: ['macOS'] # ADD 'iOS', 'tvOS', 'watchOS'
    steps:
    - name: Switch xcode to ${{ matrix.xcode }}
      uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Double-check macOS version (${{ matrix.macos }})
      run: sw_vers
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations for ${{ matrix.scheme }}
      run: xcodebuild -showdestinations -scheme ${{ matrix.scheme }}
    - name: Skip Macro Validation
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
    - uses: mxcl/xcodebuild@v2.0.0
      with:
        platform: ${{ matrix.platform }}
        scheme: ${{ matrix.scheme }}
        action: ${{ matrix.command }} 
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
        
  generate_and_deploy_docs:
    name: Build Documentation
    runs-on: ${{ matrix.macos }}
    strategy:
      fail-fast: false
      matrix:
        xcode: ['latest']
        macos: ['macos-14']
        scheme: ['Taskr']
        command: ['docbuild']
        platform: ['macOS'] # ADD 'iOS', 'tvOS', 'watchOS'
    steps:
      - name: Switch xcode to ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Double-check macOS version (${{ matrix.macos }})
        run: sw_vers
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Check xcodebuild version
        run: xcodebuild -version
      - name: Check xcode embedded SDKs
        run: xcodebuild -showsdks
      - name: Show buildable schemes
        run: xcodebuild -list
      - name: Show eligible build destinations for ${{ matrix.scheme }}
        run: xcodebuild -showdestinations -scheme ${{ matrix.scheme }}
      - name: Skip Macro Validation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - uses: mxcl/xcodebuild@v2.0.0
        with:
          platform: ${{ matrix.platform }}
          scheme: ${{ matrix.scheme }}
          action: ${{ matrix.command }}
          code-coverage: true
          verbosity: xcpretty
          upload-logs: always
      - name: Generate DocC Documentation
        run: |
          xcodebuild docbuild -scheme Lite -destination generic/platform=macOS
          if \[ -d "$(find . -name '\*.doccarchive' | head -n 1)" \]; then
            mkdir -p ./DocC-Archive
            mv $(find . -name '\*.doccarchive' | head -n 1) ./DocC-Archive
          else
            echo "No .doccarchive file found."
            exit 1
          fi
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./DocC-Archive
          keep_files: false # Set to true if you want to keep old files
